"""add temp message

Revision ID: 1aa0b6d8ac6e
Revises: 4828ae8917b9
Create Date: 2025-02-15 22:01:01.366667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa0b6d8ac6e'
down_revision: Union[str, None] = '4828ae8917b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temp_messages_id'), 'temp_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temp_messages_id'), table_name='temp_messages')
    op.drop_table('temp_messages')
    # ### end Alembic commands ###
