"""init db

Revision ID: caf1da9791a8
Revises: 
Create Date: 2025-02-16 06:18:24.282726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf1da9791a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=450), nullable=False),
    sa.Column('refresh_token', sa.String(length=450), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('access_token')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('conversation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('systemPrompt', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('maxTokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('topP', sa.Float(), nullable=False),
    sa.Column('topK', sa.Float(), nullable=False),
    sa.Column('repetitionPenalty', sa.Float(), nullable=False),
    sa.Column('minP', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversationId', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('assistant', 'user', name='messagerole'), nullable=False),
    sa.Column('feedback', sa.Enum('good', 'bad', 'non', name='messagefeedback'), nullable=False),
    sa.Column('tokenCounter', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatedAt', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversationId'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversation')
    op.drop_table('users')
    op.drop_table('tokens')
    # ### end Alembic commands ###
