"""fix: typo

Revision ID: ece005393d50
Revises: 698078d8f373
Create Date: 2025-02-16 02:43:54.464374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece005393d50'
down_revision: Union[str, None] = '698078d8f373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_token', sa.String(length=450), nullable=False))
    op.add_column('tokens', sa.Column('refresh_token', sa.String(length=450), nullable=False))
    op.drop_column('tokens', 'refresh_toke')
    op.drop_column('tokens', 'access_toke')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('access_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False))
    op.add_column('tokens', sa.Column('refresh_toke', sa.VARCHAR(length=450), autoincrement=False, nullable=False))
    op.drop_column('tokens', 'refresh_token')
    op.drop_column('tokens', 'access_token')
    # ### end Alembic commands ###
